### ISSUE TITLE
option to ignore switch statements on things like reflect.Kind

### ISSUE THREAD

**Issue by TristanSpeakEasy** [nishanths/exhaustive#51] opened 2022-08-18 09:33 UTC
Most code I have written and seen using reflect.Kind etc rarely is ever exhaustive when dealing with reflected types, so I find myself always having to add `//nolint:exhaustive`.

Would be great to have a way to ignore certain types like this via configuration of exhaustive or it to ignore those types by default

**Comment by nishanths** [comment] 2022-08-18 11:51
related: https://github.com/nishanths/exhaustive/issues/34

**Comment by nishanths** [comment] 2022-11-25 21:49
Does the `-ignore-enum-member` flag work sufficiently for your use case?

```
% exhaustive -ignore-enum-members '^reflect\.Kind$'
```

The documentation for the flag is:

```
  -ignore-enum-members regexp
        enum members matching regexp do not have to be listed to satisfy exhaustiveness
```

**Comment by nishanths** [comment] 2022-11-25 21:55
I'd incorrectly suggested the `-ignore-enum-members` flag in an earlier (now deleted) comment. I think we should add a similar `-ignore-enum-types` flag for this use case.

**Comment by xiegeo** [comment] 2022-11-26 15:21
I also run into this. I thought it was a bug because my code intended to use the default case most of the time. My 2 cents is if many cases are missing and a default statement exists, then that is clearly by design and should not fire off a warning.

**Comment by nishanths** [comment] 2022-11-26 15:26
@xiegeo: Does the existing `-default-signifies-exhaustive` flag address your use case?

```
  -default-signifies-exhaustive
    	presence of 'default' case in switch statement unconditionally satisfies exhaustiveness

If the -default-signifies-exhaustive flag is enabled, the presence of a
'default' case in a switch statement unconditionally satisfies exhaustiveness
(all enum members do not have to be listed). Enabling this flag usually tends
to counter the purpose of exhaustiveness checking, so it is not recommended
that you do so.
```

**Comment by nishanths** [comment] 2022-11-26 19:30
Commit https://github.com/nishanths/exhaustive/commit/176c4b3f18c94278e08c946227e5f9f13cbd1dbe adds an `-ignore-enum-types` flag. 

Example usage:

```
exhaustive -ignore-enum-types "^reflect.Kind$|^time.Duration$"
```

Closing this issue. Please feel free to reopen if the flag doesn't meet your needs.

**Closed by nishanths** 2022-11-26 19:30 UTC
