### ISSUE TITLE
Support type aliasing

### ISSUE THREAD

**Issue by Antonboom** [nishanths/exhaustive#7] opened 2021-04-30 08:20 UTC
Hello!

Can you look at example in https://github.com/golangci/golangci-lint/issues/1940#issuecomment-829843782

Thank u.

**Comment by nishanths** [comment] 2021-04-30 08:24
Thank you for the example. I will take a look.

**Comment by nishanths** [comment] 2021-05-24 21:01
I have not been able to take a look. If anyone else would like to, please go ahead. Please comment on the issue before beginning if possible. Thanks.

**Comment by nishanths** [comment] 2021-07-14 01:31
Hi, sorry for the delay. I tried the [nonolint.zip](https://github.com/nishanths/exhaustive/files/6812855/nonolint.zip) example shared in the related golangci-lint issue. However I wasn't able to reproduce.  Based on the output below, the issue likely originally occurred during your tries because of a golangci-lint cache issue. The issue does not occur if `$ golangci-lint cache clean` is executed before each `golangci-lint run`. 

If you see the same behavior I've shown below, please create an issue in `golangci-lint` to fix how the cache works. It appears that the cache isn't getting invalidated aggressively enough when source files have changed.

My output was obtained using:
```
nonolint % golangci-lint --version
golangci-lint has version 1.40.1 built from 625445b on 2021-05-14T16:27:59Z
```

## Output

First, I ran tested using the original code. The code does not have the `//nolint` directive. This produces diagnostic from exhaustive as expected.
```
nonolint % cat adapt.go | head -n 10 # does not have //nolint directive
package nonolint

import "example/tigers"

func adaptTigerToInt(t tigers.Cat) int {
	switch t {
	case tigers.Tiger1:
		return 1
	}
	return 0
nonolint % golangci-lint cache clean
nonolint % golangci-lint run .
adapt.go:6:2: missing cases in switch of type cats.Cat: Cat1|Cat2 (exhaustive)
	switch t {
	^
```
Next I added the `//nolint` directive to the switch statement. 
```
nonolint|1 % cat adapt.go | head -n 10
package nonolint

import "example/tigers"

func adaptTigerToInt(t tigers.Cat) int {
	switch t { //nolint:exhaustive
	case tigers.Tiger1:
		return 1
	}
	return 0
nonolint % golangci-lint cache clean
nonolint % golangci-lint run .
# ... no output ...
```
This produces no output and a zero exit code.

**However**, if I omit the `golangci-lint cache clean` before the second `golangci-lint run` command, then I see the spurious diagnostic that was reported, i.e. 
```
adapt.go:6:13: directive `//nolint:exhaustive` is unused for linter "exhaustive" (nolintlint)
	switch t { //nolint:exhaustive
```

So the underlying issue seems to be the incorrect caching in golangci-lint.

**Comment by nishanths** [comment] 2021-07-14 01:35
All that said, `exhaustive` can be improved regarding how it handles type aliases (see issue #13). But I think that is separate from the original reason behind this issue and golangci/golangci-lint#1940. 

Based on the findings in https://github.com/nishanths/exhaustive/issues/7#issuecomment-879512515, I'm closing this issue. Please feel free to reopen 🙂

**Closed by nishanths** 2021-07-14 01:35 UTC

**Comment by Antonboom** [comment] 2021-07-14 12:54
@nishanths thank u for feedback
